server:
  port: ${PORT:8080}
  servlet:
    context-path: /todox

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173}
spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/todox}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  data:
    web:
      pageable:
        page-serialization-mode: via-dto
